---

- name: Install cloud-init
  yum:
    state: present
    name:
    - cloud-init
    - gdisk
    - git

- name: Setup cloud-init datasource
  copy:
    content: |
      datasource_list: [ Azure ]
    dest: /etc/cloud/cloud.cfg.d/91-azure_datasource.cfg

- name: Copy provision script
  copy:
    src: files/provision.sh
    dest: /provision.sh
    mode: 0600
    owner: root
    group: root

- name: Copy getupengine.env
  copy:
    src: /state/getupengine.env
    dest: /state/getupengine.env

- name: Copy terraform-out.env
  copy:
    src: /state/terraform-out.env
    dest: /state/terraform-out.env

- name: Copy ssh private key
  copy:
    src: ~/.ssh/id_rsa
    dest: /state/id_rsa

- name: Deallocate app VM
  local_action: shell az vm deallocate --resource-group {{ getupcloud_azure_resource_group }} --name app

- name: Generalize app VM
  local_action: shell az vm generalize --resource-group {{ getupcloud_azure_resource_group }} --name app

- name: Create image
  local_action: shell az image create --resource-group {{ getupcloud_azure_resource_group }}  --name app --source app
